// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "soberkoder@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ltp": {
            "get": {
                "description": "GetInfo return the Last Traded Price of Bitcoin for the following currency pairs: BTC/USD, BTC/CHF, BTC/EUR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTPB"
                ],
                "summary": "GetInfo",
                "responses": {
                    "200": {
                        "description": "return the list of pairs",
                        "schema": {
                            "$ref": "#/definitions/v1.OutputResponse"
                        }
                    },
                    "400": {
                        "description": "return the error of the bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "return the error of the failure in the API",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.OutputResponse": {
            "type": "object",
            "properties": {
                "ltp": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "amount": {
                                "type": "string"
                            },
                            "pair": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://goltpb.onrender.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "goltpb api",
	Description:      "go api for a contacts CRUD",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
